// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmpjozfsriqsezobfvhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtcGpvemZzcmlxc2V6b2JmdmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NTE3NjIsImV4cCI6MjA1NDQyNzc2Mn0.FxFhI3YDDx7yMXmTHMjQ1yEgq1mUjwtbmLoTxcoVgGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);